### ISSUE TITLE
Add function/method deprecation helpers (and some other things)

### ISSUE THREAD

**Issue by mlrawlings** [brianc/node-deprecate#3]
For anyone interested, these changes have been published as [`complain`](https://www.npmjs.com/package/complain).

---

@brianc I started working on a similar module because there's some features I need that aren't supported, but I'd rather contribute back to this rather creating a whole new project.  Everything I'm thinking should be able to be done without breaking backwards compatibility.

**Add method/function helpers**
```js
deprecate.method(myProto, 'myMethodName', 'My error message');
myFunc = deprecate.function(myFunc, 'My error message');
```

These would allow you to leave a function as is, but deprecate it.  In one of my cases we have functions that are exported that we want to deprecate the use of, but they'll still be used internally and we don't want to log deprecation messages in those cases.  Of course we could do this ourselves, but it ends up with code duplication or a helper living in our project.

**Add location**
Given `test.js`:
```js
1 │ var deprecate = require('deprecate');
2 │
3 │ var someDeprecatedFunction = function() {
4 │   deprecate('someDeprecatedFunction() is deprecated');
5 │ };
6 │
7 │ someDeprecatedFunction();
```
The program would output:
```js
WARNING!!
someDeprecatedFunction() is deprecated
  at test.js:7:0
```
This location would be pulled from a stack trace and would show a level above where the `deprecate` function was called, that is not the location of the call to `deprecate` but the location of the call to the deprecated function (in this example `someDeprecatedFunction`).

**Custom location**
```js
deprecate('message', { location:'test.js:27:4' });
```
I'd like to use this for some compile-time deprecations, so the ability to pass in a location is important.  If the last argument is an object, it will be treated as an options argument and not logged.

**Browser support**
The `process.tty` (for color support) and `process.stderr` (the default stream) are not available in the browser unless polyfills are added.

I plan to use `supports-color` which is a little more robust and has a browser specific implementation (that just returns false).  It also has support to turn color on and off via environment variable or command line flag.

And if `process.stderr` is unavailable use a `console.warn` fallback.

**Once per location**
Currently the `deprecate` logs once per caller.  I'd like to switch this to once per location, that way a user can see all the places that they're using a deprecated function, but still with minimal noise.

e.g., from the example above,
```js
7 │ someDeprecatedFunction();
8 │ someDeprecatedFunction();
9 │ someDeprecatedFunction();
```
would output 3 warnings:
```js
WARNING!!
someDeprecatedFunction() is deprecated
  at test.js:7:0

WARNING!!
someDeprecatedFunction() is deprecated
  at test.js:8:0

WARNING!!
someDeprecatedFunction() is deprecated
  at test.js:9:0
```

But,
```js
11│ function foo() {
12│     someDeprecatedFunction();
13│ }
14│ 
15│ foo();
16│ foo();
```
would output only 1 warning:
```js
WARNING!!
someDeprecatedFunction() is deprecated
  at test.js:12:4
```

**Avoid doing anything in production**
if `process.env.NODE_ENV` does not equal `''`, `'development'` or `'dev'`, we'll not do anything.
```js
module.exports = function() {};
module.exports.method = function() {};
module.exports.function = function(fn) { return fn };
```
---

As I said, I'm ready to merge these changes in, so if you're open to them, let me know and I'll open a PR.  If you're not open, also please let me know so I can publish my own module.

Thanks!

**Comment by brianc** [comment]
Hey @mlrawlings all that sounds awesome! 100%!  I'm definitely open to a pull request.  Sorry for the delay in getting back to you - was buried under github notifications & this one got missed.
